# Generated by Django 5.2 on 2026-02-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='شابک')),
                ('genre', models.CharField(choices=[('FI', 'داستانی'), ('SF', 'علمی-تخیلی'), ('HI', 'تاریخی'), ('BI', 'زندگینامه'), ('PR', 'برنامه\u200cنویسی')], max_length=2, verbose_name='ژانر')),
                ('published_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('page_count', models.IntegerField(verbose_name='تعداد صفحات')),
                ('available_copies', models.IntegerField(default=1, verbose_name='تعداد نسخه\u200cهای موجود')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='learn_CBV.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
